apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: urpuu1xdn-go
  janus-idp.io/tekton: urpuu1xdn-go
  backstage.io/kubernetes-id: urpuu1xdn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: urpuu1xdn-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
